config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get '/auth/github', as: 'github_login'
  get '/auth/github/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/profile', to: 'users#show'
  get '/repositories', to: 'repositories#index'
  get '/following', to: 'following#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following
  attr_reader :name,
              :recent_activity

 def initialize(data)
   @name = data[:name]
   @recent_activity = data[:recent_activity]
 end

 def self.find_all(user)
   github_service = GithubService.new(user)
   data = github_service.following
   data.map {|data| Following.new(data)}
 end

end

app/models/organization.rb
class Organization
  attr_reader :name

  def initialize(name)
    @name = name
  end
end

app/models/repository.rb
class Repository
  attr_reader :name

  def initialize(name)
    @name = name
  end

  def self.find_all(user)
    github_service = GithubService.new(user)
    data = github_service.repositories
    data.map {|data| Repository.new(data)}
  end
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.name               = auth_info.info.name
      new_user.username           = auth_info.info.nickname
      new_user.oauth_token        = auth_info.credentials.token
      new_user.oauth_token_secret = auth_info.credentials.secret
      new_user.profile_picture    = auth_info.info.images
    end
  end
end

app/models/user_dashboard.rb
class UserDashboard
  attr_reader :num_followers,
              :num_following,
              :profile_picture,
              :num_starred_repos,
              :recent_activity

  def initialize(user)
    github_service = GithubService.new(user)
    @num_followers = github_service.num_followers
    @num_following = github_service.num_following
    @num_starred_repos = github_service.num_starred_repos
    @profile_picture = github_service.profile_picture
    @recent_activity = github_service.recent_activity
  end
end

app/models/user_profile.rb
class UserProfile
  attr_reader :num_followers,
              :num_following,
              :profile_picture,
              :num_starred_repos,
              :recent_activity,
              :organizations

  def initialize(user)
    github_service = GithubService.new(user)
    @num_followers = github_service.num_followers
    @num_following = github_service.num_following
    @num_starred_repos = github_service.num_starred_repos
    @profile_picture = github_service.profile_picture
    @recent_activity = github_service.recent_activity
    @organizations = github_service.organizations.map {|org_data| Organization.new(org_data)}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/following_controller.rb
class FollowingController < ApplicationController
  def index
    @following = Following.find_all(current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  def index
    @repositories = Repository.find_all(current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to profile_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user_profile = UserProfile.new(current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/following/index.html.erb
<h2 class = "text-center">People You are Following</h2>

<% @following.each do |following| %>
  <div class="card">
    <div class="card-header">
      <h4 class = "name"><%= following.name %></h4>
    </div>
    <div class="card-body">
      <h5>5 Latest Commits</h5>
      <% following.recent_activity[0..4].each do |activity| %>
          <br>
          <span class="badge badge-pill badge-primary commit-repo"> <%= activity[:repo] %></span>
          <label class = "commit-message"><%= activity[:message] %></label>
        <% end %>
    </div>
  </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apicurious</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
  <a class="navbar-brand" href="#">
    <img class = "logo" src="http://vannguyen.me/images/githubpurple.png" alt="octo-cat">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="#">Pull Requests</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Issues</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Marketplace</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Explore</a>
      </li>
    </ul>
  </div>
  <% if current_user %>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
          <img class = "picture-navbar" src="<%= current_user[:profile_picture] %>" alt="dropdown link">
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <span class="dropdown-item"><%= link_to "Profile", profile_path %></span>
          <span class="dropdown-item"><%= link_to "Log Out", logout_path, method: :delete %></span>
        </div>
      </li>
    </ul>
  </div>
  <% else %>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Login with Github", github_login_path %>
      </li>
    </ul>
  </div>
  <% end %>
</div>
</nav>
<div class = "container">

    <%= yield %>
  </div>
  </body>
</html>

app/views/repositories/index.html.erb
<h2 class = "text-center">Your Repositories</h2>

<% @repositories.each do |repo| %>
<h4><span class="badge badge-primary repo"><%= repo.name %> </span></h4><br>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <img class = "profile-picture" src="<%= @user_profile.profile_picture %>" alt="user_profile_picture">
      <h5>Organizations</h5>
      <% @user_profile.organizations.each do |org| %>
      <h4><span class="badge badge-light organization"><%= org.name %></span></h5> <br>
      <% end %>
    </div>
    <div class="col-md-9">
      <ul class = "nav nav-fill">
        <li class = "nav-item">
          Overview
        </li>
        <li class = "nav-item">
          <%= link_to "Repositories", repositories_path %>
        </li>
        <li class = "nav-item">
          <%= "Starred (#{@user_profile.num_starred_repos})" %>
        </li>
        <li class = "nav-item">
          <%= "Followers (#{@user_profile.num_followers})" %>
        </li>
        <li class = "nav-item">
          <%= link_to "Following (#{@user_profile.num_following})", following_path %>
        </li>
      </ul>
</div>


</div>
  <h4 class = "text-center">Recent Activity</h4>
  <br>
    <% @user_profile.recent_activity.each do |activity| %>
  <br><br>
  <span class="badge badge-primary commit-repo"> <%= activity[:repo] %></span>
  <label class = "commit-message"><%= activity[:message] %></label>
  <% end %>

</div>